import { withMemberServiceFallback } from "@/lib/member-service-history";
import type { Bill, BillVideo, Cosponsor, Member, MemberVote, UpdateEvent, Vote } from "@/types/capitol";

const memberRecords: Member[] = [
  {
    bioguideId: "O000172",
    firstName: "Alexandria",
    lastName: "Ocasio-Cortez",
    fullName: "Rep. Alexandria Ocasio-Cortez",
    party: "Democrat",
    state: "NY",
    district: "14",
    chamber: "House",
    active: true,
    term: "119th Congress",
    termsInOffice: 4,
    firstElectedDate: "2018-11-06",
    nextElectionDate: "2026-11-03",
    photoUrl: "https://www.congress.gov/img/member/o000172_200.jpg",
    officialUrl: "https://ocasio-cortez.house.gov/",
    sourceUrl: "https://www.congress.gov/member/alexandria-ocasio-cortez/O000172",
    description: "House member from New York with committee, sponsorship, and roll-call records ready for source review."
  },
  {
    bioguideId: "S000148",
    firstName: "Charles",
    lastName: "Schumer",
    fullName: "Sen. Charles E. Schumer",
    party: "Democrat",
    state: "NY",
    chamber: "Senate",
    active: true,
    term: "119th Congress",
    photoUrl: "https://www.congress.gov/img/member/s000148_200.jpg",
    officialUrl: "https://www.schumer.senate.gov/",
    sourceUrl: "https://www.congress.gov/member/charles-schumer/S000148",
    description: "Senator from New York included for beta testers reviewing state-based federal representation."
  },
  {
    bioguideId: "G000555",
    firstName: "Kirsten",
    lastName: "Gillibrand",
    fullName: "Sen. Kirsten E. Gillibrand",
    party: "Democrat",
    state: "NY",
    chamber: "Senate",
    active: true,
    term: "119th Congress",
    photoUrl: "https://www.congress.gov/img/member/g000555_200.jpg",
    officialUrl: "https://www.gillibrand.senate.gov/",
    sourceUrl: "https://www.congress.gov/member/kirsten-gillibrand/G000555",
    description: "Senator from New York included for district-personalized beta search and profile testing."
  },
  {
    bioguideId: "P000145",
    firstName: "Alex",
    lastName: "Padilla",
    fullName: "Sen. Alex Padilla",
    party: "Democrat",
    state: "CA",
    chamber: "Senate",
    active: true,
    term: "119th Congress",
    photoUrl: "https://www.congress.gov/img/member/p000145_200.jpg",
    officialUrl: "https://www.padilla.senate.gov/",
    sourceUrl: "https://www.congress.gov/member/alex-padilla/P000145",
    description: "Senator from California included for beta testers reviewing local federal representation."
  },
  {
    bioguideId: "S001150",
    firstName: "Adam",
    lastName: "Schiff",
    fullName: "Sen. Adam B. Schiff",
    party: "Democrat",
    state: "CA",
    chamber: "Senate",
    active: true,
    term: "119th Congress",
    photoUrl: "https://www.congress.gov/img/member/s001150_200.jpg",
    officialUrl: "https://www.schiff.senate.gov/",
    sourceUrl: "https://www.congress.gov/member/adam-schiff/S001150",
    description: "Senator from California included for state-based tester onboarding and search filtering."
  },
  {
    bioguideId: "FCA030",
    firstName: "Laura",
    lastName: "Friedman",
    fullName: "Rep. Laura Friedman",
    party: "Democrat",
    state: "CA",
    district: "30",
    chamber: "House",
    active: true,
    term: "119th Congress",
    termsInOffice: 1,
    firstElectedDate: "2024-11-05",
    nextElectionDate: "2026-11-03",
    officialUrl: "https://friedman.house.gov/",
    sourceUrl: "https://friedman.house.gov/",
    description: "House member from California's 30th District included for Montrose, Glendale, and CA-30 beta district matching."
  },
  {
    bioguideId: "G000585",
    firstName: "Jimmy",
    lastName: "Gomez",
    fullName: "Rep. Jimmy Gomez",
    party: "Democrat",
    state: "CA",
    district: "34",
    chamber: "House",
    active: true,
    term: "119th Congress",
    photoUrl: "https://www.congress.gov/img/member/g000585_200.jpg",
    officialUrl: "https://gomez.house.gov/",
    sourceUrl: "https://www.congress.gov/member/jimmy-gomez/G000585",
    description: "House member from California's 34th District included for Los Angeles beta district matching."
  },
  {
    bioguideId: "W000817",
    firstName: "Elizabeth",
    lastName: "Warren",
    fullName: "Sen. Elizabeth Warren",
    party: "Democrat",
    state: "MA",
    chamber: "Senate",
    active: true,
    term: "119th Congress",
    photoUrl: "https://www.congress.gov/img/member/w000817_200.jpg",
    officialUrl: "https://www.warren.senate.gov/",
    sourceUrl: "https://www.congress.gov/member/elizabeth-warren/W000817",
    description: "Senator from Massachusetts included for beta testers reviewing state-based federal representation."
  },
  {
    bioguideId: "M000133",
    firstName: "Edward",
    lastName: "Markey",
    fullName: "Sen. Edward J. Markey",
    party: "Democrat",
    state: "MA",
    chamber: "Senate",
    active: true,
    term: "119th Congress",
    photoUrl: "https://www.congress.gov/img/member/m000133_200.jpg",
    officialUrl: "https://www.markey.senate.gov/",
    sourceUrl: "https://www.congress.gov/member/edward-markey/M000133",
    description: "Senator from Massachusetts included for Boston-area beta onboarding and search testing."
  },
  {
    bioguideId: "P000617",
    firstName: "Ayanna",
    lastName: "Pressley",
    fullName: "Rep. Ayanna Pressley",
    party: "Democrat",
    state: "MA",
    district: "7",
    chamber: "House",
    active: true,
    term: "119th Congress",
    photoUrl: "https://www.congress.gov/img/member/p000617_200.jpg",
    officialUrl: "https://pressley.house.gov/",
    sourceUrl: "https://www.congress.gov/member/ayanna-pressley/P000617",
    description: "House member from Massachusetts's 7th District included for Boston-area beta district matching."
  },
  {
    bioguideId: "C001098",
    firstName: "Ted",
    lastName: "Cruz",
    fullName: "Sen. Ted Cruz",
    party: "Republican",
    state: "TX",
    chamber: "Senate",
    active: true,
    term: "119th Congress",
    photoUrl: "https://www.congress.gov/img/member/c001098_200.jpg",
    officialUrl: "https://www.cruz.senate.gov/",
    sourceUrl: "https://www.congress.gov/member/ted-cruz/C001098",
    description: "Senator from Texas with recent votes, sponsored legislation, and public record links grouped for inspection."
  },
  {
    bioguideId: "C001056",
    firstName: "John",
    lastName: "Cornyn",
    fullName: "Sen. John Cornyn",
    party: "Republican",
    state: "TX",
    chamber: "Senate",
    active: true,
    term: "119th Congress",
    photoUrl: "https://www.congress.gov/img/member/c001056_200.jpg",
    officialUrl: "https://www.cornyn.senate.gov/",
    sourceUrl: "https://www.congress.gov/member/john-cornyn/C001056",
    description: "Senator from Texas included for Austin, Dallas, and Houston beta tester representation."
  },
  {
    bioguideId: "M001157",
    firstName: "Michael",
    lastName: "McCaul",
    fullName: "Rep. Michael McCaul",
    party: "Republican",
    state: "TX",
    district: "10",
    chamber: "House",
    active: true,
    term: "119th Congress",
    photoUrl: "https://www.congress.gov/img/member/m001157_200.jpg",
    officialUrl: "https://mccaul.house.gov/",
    sourceUrl: "https://www.congress.gov/member/michael-mccaul/M001157",
    description: "House member from Texas's 10th District included for Austin beta district matching."
  },
  {
    bioguideId: "S000033",
    firstName: "Bernard",
    lastName: "Sanders",
    fullName: "Sen. Bernie Sanders",
    party: "Independent",
    state: "VT",
    chamber: "Senate",
    active: true,
    term: "119th Congress",
    photoUrl: "https://www.congress.gov/img/member/s000033_200.jpg",
    officialUrl: "https://www.sanders.senate.gov/",
    sourceUrl: "https://www.congress.gov/member/bernard-sanders/S000033",
    description: "Independent senator from Vermont with issue, sponsorship, and roll-call activity shown in neutral context."
  },
  {
    bioguideId: "M001153",
    firstName: "Lisa",
    lastName: "Murkowski",
    fullName: "Sen. Lisa Murkowski",
    party: "Republican",
    state: "AK",
    chamber: "Senate",
    active: true,
    term: "119th Congress",
    photoUrl: "https://www.congress.gov/img/member/m001153_200.jpg",
    officialUrl: "https://www.murkowski.senate.gov/",
    sourceUrl: "https://www.congress.gov/member/lisa-murkowski/M001153",
    description: "Senator from Alaska included to demonstrate cross-party filtering and chamber-specific vote views."
  }
];

export const members: Member[] = memberRecords.map(withMemberServiceFallback);

export const bills: Bill[] = [
  {
    id: "demo-hr-4021",
    congress: 119,
    billType: "HR",
    billNumber: "4021",
    displayNumber: "H.R. 4021",
    title: "Civic Data Transparency Act",
    shortTitle: "Civic Data Transparency Act",
    sponsorBioguideId: "O000172",
    policyArea: "Government Operations",
    introducedDate: "2026-04-10",
    committeeName: "House Oversight Committee",
    latestActionText: "Referred to committee for review.",
    latestActionDate: "2026-04-21",
    summary:
      "The Civic Data Transparency Act would require selected congressional records and bill status updates to be published in a standard digital format so the public can more easily track legislative changes, official actions, and government records.",
    sourceUrl: "https://www.congress.gov/"
  },
  {
    id: "demo-s-1188",
    congress: 119,
    billType: "S",
    billNumber: "1188",
    displayNumber: "S. 1188",
    title: "Border Infrastructure Review Act",
    shortTitle: "Border Infrastructure Review Act",
    sponsorBioguideId: "C001098",
    policyArea: "Homeland Security",
    introducedDate: "2026-03-04",
    committeeName: "Senate Homeland Security Committee",
    latestActionText: "Placed on Senate legislative calendar.",
    latestActionDate: "2026-03-17",
    summary:
      "The Border Infrastructure Review Act would require an annual review of border infrastructure projects, including project costs, timelines, delays, and implementation progress.",
    sourceUrl: "https://www.congress.gov/"
  },
  {
    id: "demo-s-2710",
    congress: 119,
    billType: "S",
    billNumber: "2045",
    displayNumber: "S. 2045",
    title: "Affordable Childcare Act",
    shortTitle: "Affordable Childcare Act",
    sponsorBioguideId: "S000033",
    policyArea: "Health",
    introducedDate: "2026-01-21",
    committeeName: "Senate HELP Committee",
    latestActionText: "Committee hearings held.",
    latestActionDate: "2026-02-06",
    summary:
      "The Affordable Childcare Act would expand child care affordability grants and require public reporting on access, family costs, provider availability, and workforce stability.",
    sourceUrl: "https://www.congress.gov/"
  },
  {
    id: "demo-s-449",
    congress: 119,
    billType: "S",
    billNumber: "449",
    displayNumber: "S. 449",
    title: "Arctic Resilience and Ports Act",
    shortTitle: "Arctic Resilience and Ports Act",
    sponsorBioguideId: "M001153",
    policyArea: "Transportation and Public Works",
    introducedDate: "2026-01-29",
    committeeName: "Senate Commerce Committee",
    latestActionText: "Reported by committee with amendments.",
    latestActionDate: "2026-04-02",
    summary:
      "The Arctic Resilience and Ports Act would authorize planning funds for Arctic port resilience, maritime safety, supply-chain reliability, and related infrastructure projects.",
    sourceUrl: "https://www.congress.gov/"
  }
];

export const cosponsors: Cosponsor[] = [
  { billId: "demo-hr-4021", memberBioguideId: "S000033", joinedAt: "2026-04-23" },
  { billId: "demo-s-2710", memberBioguideId: "O000172", joinedAt: "2026-02-15" },
  { billId: "demo-s-449", memberBioguideId: "C001098", joinedAt: "2026-04-04" },
  { billId: "demo-s-1188", memberBioguideId: "M001153", joinedAt: "2026-03-20" }
];

export const billVideos: BillVideo[] = [
  {
    id: "video-s-2710-hearing",
    billId: "demo-s-2710",
    title: "Child care assistance oversight hearing archive",
    speaker: "Senate HELP Committee",
    role: "Official hearing source",
    source: "U.S. Senate HELP Committee",
    sourceKind: "Official committee video",
    verifiedAt: "2026-05-19",
    publishedAt: "2026-02-12",
    duration: "Hearing archive",
    videoUrl: "https://www.help.senate.gov/hearings/restoring-integrity-preventing-fraud-in-child-care-assistance-programs",
    type: "Committee Hearing",
    summary: "Official HELP Committee hearing page for child care assistance comments, witnesses, and committee video records."
  },
  {
    id: "video-s-2710-floor",
    billId: "demo-s-2710",
    title: "Senate floor video and Congressional Record source",
    speaker: "U.S. Senate floor",
    role: "Floor remarks source",
    source: "Congress.gov Video",
    sourceKind: "Official floor video",
    verifiedAt: "2026-05-19",
    publishedAt: "2026-04-03",
    duration: "Source feed",
    videoUrl: "https://www.congress.gov/video",
    type: "Floor Speech",
    summary: "Official Congress.gov video destination for floor proceedings and member remarks connected to legislative debate."
  },
  {
    id: "video-hr-4021-floor",
    billId: "demo-hr-4021",
    title: "House floor proceedings video source",
    speaker: "U.S. House floor",
    role: "Floor remarks source",
    source: "HouseLive",
    sourceKind: "Official floor video",
    verifiedAt: "2026-05-19",
    publishedAt: "2026-04-28",
    duration: "Live archive",
    videoUrl: "https://live.house.gov/",
    type: "Floor Speech",
    summary: "Official House floor video destination for proceedings, debate, and public-record transparency remarks."
  },
  {
    id: "video-s-1188-hearing",
    billId: "demo-s-1188",
    title: "Homeland security hearing and oversight archive",
    speaker: "Senate Homeland Security Committee",
    role: "Official hearing source",
    source: "U.S. Senate HSGAC",
    sourceKind: "Official committee video",
    verifiedAt: "2026-05-19",
    publishedAt: "2026-03-17",
    duration: "Hearing archive",
    videoUrl: "https://www.hsgac.senate.gov/hearings/",
    type: "Committee Hearing",
    summary: "Official Senate homeland security hearing archive for oversight comments, testimony, and implementation discussions."
  },
  {
    id: "video-s-1188-floor",
    billId: "demo-s-1188",
    title: "Senate roll-call and debate source",
    speaker: "U.S. Senate floor",
    role: "Vote and debate source",
    source: "U.S. Senate Roll Call Votes",
    sourceKind: "Official vote record",
    verifiedAt: "2026-05-19",
    publishedAt: "2026-03-24",
    duration: "Source feed",
    videoUrl: "https://www.senate.gov/legislative/votes_new.htm",
    type: "Public Statement",
    summary: "Official Senate voting source for roll-call context, floor action, and follow-up debate references."
  },
  {
    id: "video-s-449-hearing",
    billId: "demo-s-449",
    title: "U.S. maritime investments in the Arctic field hearing",
    speaker: "Senate Commerce Committee",
    role: "Official hearing source",
    source: "U.S. Senate Commerce Committee",
    sourceKind: "Official committee video",
    verifiedAt: "2026-05-19",
    publishedAt: "2026-02-20",
    duration: "Hearing archive",
    videoUrl: "https://www.commerce.senate.gov/meetings/subcommittee-field-hearing-on-u-s-maritime-investments-in-the-arctic/",
    type: "Committee Hearing",
    summary: "Official Commerce Committee field hearing source for Arctic infrastructure, maritime investment, and port resilience discussion."
  }
];

export const votes: Vote[] = [
  {
    id: "demo-vote-house-142",
    congress: 119,
    chamber: "House",
    rollCall: "142",
    question: "On passage of H.R. 4021",
    result: "Passed",
    voteDate: "2026-04-28",
    yesCount: 228,
    noCount: 206,
    presentCount: 0,
    notVotingCount: 1,
    billId: "demo-hr-4021",
    explanation: "Generated demo explanation: the vote advanced a public-records transparency bill out of the House.",
    sourceUrl: "https://clerk.house.gov/Votes"
  },
  {
    id: "demo-vote-senate-68",
    congress: 119,
    chamber: "Senate",
    rollCall: "68",
    question: "On cloture for S. 1188",
    result: "Cloture rejected",
    voteDate: "2026-03-24",
    yesCount: 46,
    noCount: 51,
    presentCount: 0,
    notVotingCount: 3,
    billId: "demo-s-1188",
    explanation: "Generated demo explanation: the motion would have limited debate and moved the bill closer to final passage.",
    sourceUrl: "https://www.senate.gov/legislative/votes_new.htm"
  },
  {
    id: "demo-vote-senate-77",
    congress: 119,
    chamber: "Senate",
    rollCall: "77",
    question: "On amendment to S. 2045",
    result: "Agreed to",
    voteDate: "2026-04-03",
    yesCount: 64,
    noCount: 28,
    presentCount: 0,
    notVotingCount: 8,
    billId: "demo-s-2710",
    explanation: "Generated demo explanation: the amendment added reporting requirements for rural health grant recipients.",
    sourceUrl: "https://www.senate.gov/legislative/votes_new.htm"
  }
];

export const memberVotes: MemberVote[] = [
  { voteId: "demo-vote-house-142", memberBioguideId: "O000172", position: "Yes" },
  { voteId: "demo-vote-senate-68", memberBioguideId: "C001098", position: "Yes" },
  { voteId: "demo-vote-senate-68", memberBioguideId: "S000033", position: "No" },
  { voteId: "demo-vote-senate-68", memberBioguideId: "M001153", position: "Present" },
  { voteId: "demo-vote-senate-77", memberBioguideId: "C001098", position: "No" },
  { voteId: "demo-vote-senate-77", memberBioguideId: "S000033", position: "Yes" },
  { voteId: "demo-vote-senate-77", memberBioguideId: "M001153", position: "Yes" }
];

export const updateEvents: UpdateEvent[] = [
  {
    id: "event-1",
    targetType: "bill",
    targetId: "demo-hr-4021",
    title: "Bill advanced",
    body: "H.R. 4021 received a recorded House vote in the demo ledger.",
    occurredAt: "2026-04-28",
    sourceUrl: "https://clerk.house.gov/Votes"
  },
  {
    id: "event-2",
    targetType: "member",
    targetId: "S000033",
    title: "New recorded vote",
    body: "A Senate amendment vote was added to the member activity feed.",
    occurredAt: "2026-04-03",
    sourceUrl: "https://www.senate.gov/legislative/votes_new.htm"
  },
  {
    id: "event-3",
    targetType: "bill",
    targetId: "demo-s-449",
    title: "Committee action",
    body: "The Arctic Resilience and Ports Act was reported by committee with amendments.",
    occurredAt: "2026-04-02",
    sourceUrl: "https://www.congress.gov/"
  }
];
