import { withMemberServiceFallback } from "@/lib/member-service-history";
import type { Bill, BillAction, BillVideo, Cosponsor, Member, MemberVote, UpdateEvent, Vote } from "@/types/capitol";

const memberRecords: Member[] = [
  {
    bioguideId: "O000172",
    firstName: "Alexandria",
    lastName: "Ocasio-Cortez",
    fullName: "Rep. Alexandria Ocasio-Cortez",
    party: "Democrat",
    state: "NY",
    district: "14",
    chamber: "House",
    active: true,
    term: "119th Congress",
    termsInOffice: 4,
    firstElectedDate: "2018-11-06",
    nextElectionDate: "2026-11-03",
    photoUrl: "https://www.congress.gov/img/member/o000172_200.jpg",
    officialUrl: "https://ocasio-cortez.house.gov/",
    sourceUrl: "https://www.congress.gov/member/alexandria-ocasio-cortez/O000172",
    description: "House member from New York with committee, sponsorship, and roll-call records ready for source review."
  },
  {
    bioguideId: "S000148",
    firstName: "Charles",
    lastName: "Schumer",
    fullName: "Sen. Charles E. Schumer",
    party: "Democrat",
    state: "NY",
    chamber: "Senate",
    active: true,
    term: "119th Congress",
    photoUrl: "https://www.congress.gov/img/member/s000148_200.jpg",
    officialUrl: "https://www.schumer.senate.gov/",
    sourceUrl: "https://www.congress.gov/member/charles-schumer/S000148",
    description: "Senator from New York included for beta testers reviewing state-based federal representation."
  },
  {
    bioguideId: "G000555",
    firstName: "Kirsten",
    lastName: "Gillibrand",
    fullName: "Sen. Kirsten E. Gillibrand",
    party: "Democrat",
    state: "NY",
    chamber: "Senate",
    active: true,
    term: "119th Congress",
    photoUrl: "https://www.congress.gov/img/member/g000555_200.jpg",
    officialUrl: "https://www.gillibrand.senate.gov/",
    sourceUrl: "https://www.congress.gov/member/kirsten-gillibrand/G000555",
    description: "Senator from New York included for district-personalized beta search and profile testing."
  },
  {
    bioguideId: "P000145",
    firstName: "Alex",
    lastName: "Padilla",
    fullName: "Sen. Alex Padilla",
    party: "Democrat",
    state: "CA",
    chamber: "Senate",
    active: true,
    term: "119th Congress",
    photoUrl: "https://www.congress.gov/img/member/p000145_200.jpg",
    officialUrl: "https://www.padilla.senate.gov/",
    sourceUrl: "https://www.congress.gov/member/alex-padilla/P000145",
    description: "Senator from California included for beta testers reviewing local federal representation."
  },
  {
    bioguideId: "S001150",
    firstName: "Adam",
    lastName: "Schiff",
    fullName: "Sen. Adam B. Schiff",
    party: "Democrat",
    state: "CA",
    chamber: "Senate",
    active: true,
    term: "119th Congress",
    photoUrl: "https://www.congress.gov/img/member/s001150_200.jpg",
    officialUrl: "https://www.schiff.senate.gov/",
    sourceUrl: "https://www.congress.gov/member/adam-schiff/S001150",
    description: "Senator from California included for state-based tester onboarding and search filtering."
  },
  {
    bioguideId: "FCA030",
    firstName: "Laura",
    lastName: "Friedman",
    fullName: "Rep. Laura Friedman",
    party: "Democrat",
    state: "CA",
    district: "30",
    chamber: "House",
    active: true,
    term: "119th Congress",
    termsInOffice: 1,
    firstElectedDate: "2024-11-05",
    nextElectionDate: "2026-11-03",
    officialUrl: "https://friedman.house.gov/",
    sourceUrl: "https://friedman.house.gov/",
    description: "House member from California's 30th District included for Montrose, Glendale, and CA-30 beta district matching."
  },
  {
    bioguideId: "G000585",
    firstName: "Jimmy",
    lastName: "Gomez",
    fullName: "Rep. Jimmy Gomez",
    party: "Democrat",
    state: "CA",
    district: "34",
    chamber: "House",
    active: true,
    term: "119th Congress",
    photoUrl: "https://www.congress.gov/img/member/g000585_200.jpg",
    officialUrl: "https://gomez.house.gov/",
    sourceUrl: "https://www.congress.gov/member/jimmy-gomez/G000585",
    description: "House member from California's 34th District included for Los Angeles beta district matching."
  },
  {
    bioguideId: "W000817",
    firstName: "Elizabeth",
    lastName: "Warren",
    fullName: "Sen. Elizabeth Warren",
    party: "Democrat",
    state: "MA",
    chamber: "Senate",
    active: true,
    term: "119th Congress",
    photoUrl: "https://www.congress.gov/img/member/w000817_200.jpg",
    officialUrl: "https://www.warren.senate.gov/",
    sourceUrl: "https://www.congress.gov/member/elizabeth-warren/W000817",
    description: "Senator from Massachusetts included for beta testers reviewing state-based federal representation."
  },
  {
    bioguideId: "M000133",
    firstName: "Edward",
    lastName: "Markey",
    fullName: "Sen. Edward J. Markey",
    party: "Democrat",
    state: "MA",
    chamber: "Senate",
    active: true,
    term: "119th Congress",
    photoUrl: "https://www.congress.gov/img/member/m000133_200.jpg",
    officialUrl: "https://www.markey.senate.gov/",
    sourceUrl: "https://www.congress.gov/member/edward-markey/M000133",
    description: "Senator from Massachusetts included for Boston-area beta onboarding and search testing."
  },
  {
    bioguideId: "P000617",
    firstName: "Ayanna",
    lastName: "Pressley",
    fullName: "Rep. Ayanna Pressley",
    party: "Democrat",
    state: "MA",
    district: "7",
    chamber: "House",
    active: true,
    term: "119th Congress",
    photoUrl: "https://www.congress.gov/img/member/p000617_200.jpg",
    officialUrl: "https://pressley.house.gov/",
    sourceUrl: "https://www.congress.gov/member/ayanna-pressley/P000617",
    description: "House member from Massachusetts's 7th District included for Boston-area beta district matching."
  },
  {
    bioguideId: "C001098",
    firstName: "Ted",
    lastName: "Cruz",
    fullName: "Sen. Ted Cruz",
    party: "Republican",
    state: "TX",
    chamber: "Senate",
    active: true,
    term: "119th Congress",
    photoUrl: "https://www.congress.gov/img/member/c001098_200.jpg",
    officialUrl: "https://www.cruz.senate.gov/",
    sourceUrl: "https://www.congress.gov/member/ted-cruz/C001098",
    description: "Senator from Texas with recent votes, sponsored legislation, and public record links grouped for inspection."
  },
  {
    bioguideId: "C001056",
    firstName: "John",
    lastName: "Cornyn",
    fullName: "Sen. John Cornyn",
    party: "Republican",
    state: "TX",
    chamber: "Senate",
    active: true,
    term: "119th Congress",
    photoUrl: "https://www.congress.gov/img/member/c001056_200.jpg",
    officialUrl: "https://www.cornyn.senate.gov/",
    sourceUrl: "https://www.congress.gov/member/john-cornyn/C001056",
    description: "Senator from Texas included for Austin, Dallas, and Houston beta tester representation."
  },
  {
    bioguideId: "M001157",
    firstName: "Michael",
    lastName: "McCaul",
    fullName: "Rep. Michael McCaul",
    party: "Republican",
    state: "TX",
    district: "10",
    chamber: "House",
    active: true,
    term: "119th Congress",
    photoUrl: "https://www.congress.gov/img/member/m001157_200.jpg",
    officialUrl: "https://mccaul.house.gov/",
    sourceUrl: "https://www.congress.gov/member/michael-mccaul/M001157",
    description: "House member from Texas's 10th District included for Austin beta district matching."
  },
  {
    bioguideId: "S000033",
    firstName: "Bernard",
    lastName: "Sanders",
    fullName: "Sen. Bernie Sanders",
    party: "Independent",
    state: "VT",
    chamber: "Senate",
    active: true,
    term: "119th Congress",
    photoUrl: "https://www.congress.gov/img/member/s000033_200.jpg",
    officialUrl: "https://www.sanders.senate.gov/",
    sourceUrl: "https://www.congress.gov/member/bernard-sanders/S000033",
    description: "Independent senator from Vermont with issue, sponsorship, and roll-call activity shown in neutral context."
  },
  {
    bioguideId: "M001153",
    firstName: "Lisa",
    lastName: "Murkowski",
    fullName: "Sen. Lisa Murkowski",
    party: "Republican",
    state: "AK",
    chamber: "Senate",
    active: true,
    term: "119th Congress",
    photoUrl: "https://www.congress.gov/img/member/m001153_200.jpg",
    officialUrl: "https://www.murkowski.senate.gov/",
    sourceUrl: "https://www.congress.gov/member/lisa-murkowski/M001153",
    description: "Senator from Alaska included to demonstrate cross-party filtering and chamber-specific vote views."
  },
  {
    bioguideId: "R000614",
    firstName: "Chip",
    lastName: "Roy",
    fullName: "Rep. Chip Roy",
    party: "Republican",
    state: "TX",
    district: "21",
    chamber: "House",
    active: true,
    term: "119th Congress",
    termsInOffice: 4,
    firstElectedDate: "2018-11-06",
    nextElectionDate: "2026-11-03",
    photoUrl: "https://www.congress.gov/img/member/r000614_200.jpg",
    officialUrl: "https://roy.house.gov/",
    sourceUrl: "https://www.congress.gov/member/chip-roy/R000614",
    description: "House member from Texas's 21st District included as the sponsor of a current 119th Congress bill in the beta dataset."
  },
  {
    bioguideId: "W000821",
    firstName: "Bruce",
    lastName: "Westerman",
    fullName: "Rep. Bruce Westerman",
    party: "Republican",
    state: "AR",
    district: "4",
    chamber: "House",
    active: true,
    term: "119th Congress",
    termsInOffice: 6,
    firstElectedDate: "2014-11-04",
    nextElectionDate: "2026-11-03",
    photoUrl: "https://www.congress.gov/img/member/w000821_200.jpg",
    officialUrl: "https://westerman.house.gov/",
    sourceUrl: "https://www.congress.gov/member/bruce-westerman/W000821",
    description: "House member from Arkansas's 4th District included as an outside-state sponsor for source-backed bill testing."
  },
  {
    bioguideId: "S001184",
    firstName: "Tim",
    lastName: "Scott",
    fullName: "Sen. Tim Scott",
    party: "Republican",
    state: "SC",
    chamber: "Senate",
    active: true,
    term: "119th Congress",
    termsInOffice: 3,
    firstElectedDate: "2014-11-04",
    nextElectionDate: "2028-11-07",
    photoUrl: "https://www.congress.gov/img/member/s001184_200.jpg",
    officialUrl: "https://www.scott.senate.gov/",
    sourceUrl: "https://www.congress.gov/member/tim-scott/S001184",
    description: "Senator from South Carolina included as the sponsor of a health bill referred to the Senate Finance Committee."
  },
  {
    bioguideId: "S001198",
    firstName: "Dan",
    lastName: "Sullivan",
    fullName: "Sen. Dan Sullivan",
    party: "Republican",
    state: "AK",
    chamber: "Senate",
    active: true,
    term: "119th Congress",
    termsInOffice: 2,
    firstElectedDate: "2014-11-04",
    nextElectionDate: "2026-11-03",
    photoUrl: "https://www.congress.gov/img/member/s001198_200.jpg",
    officialUrl: "https://www.sullivan.senate.gov/",
    sourceUrl: "https://www.congress.gov/member/dan-sullivan/S001198",
    description: "Senator from Alaska included as the sponsor of a current 119th Congress social welfare bill."
  },
  {
    bioguideId: "W000790",
    firstName: "Raphael",
    lastName: "Warnock",
    fullName: "Sen. Raphael G. Warnock",
    party: "Democrat",
    state: "GA",
    chamber: "Senate",
    active: true,
    term: "119th Congress",
    termsInOffice: 2,
    firstElectedDate: "2021-01-05",
    nextElectionDate: "2028-11-07",
    photoUrl: "https://www.congress.gov/img/member/w000790_200.jpg",
    officialUrl: "https://www.warnock.senate.gov/",
    sourceUrl: "https://www.congress.gov/member/raphael-warnock/W000790",
    description: "Senator from Georgia included as an outside-state cosponsor so testers can inspect cross-state bill relationships."
  },
  {
    bioguideId: "P000197",
    firstName: "Nancy",
    lastName: "Pelosi",
    fullName: "Rep. Nancy Pelosi",
    party: "Democrat",
    state: "CA",
    district: "11",
    chamber: "House",
    active: true,
    term: "119th Congress",
    termsInOffice: 20,
    firstElectedDate: "1987-06-02",
    nextElectionDate: "2026-11-03",
    photoUrl: "https://www.congress.gov/img/member/p000197_200.jpg",
    officialUrl: "https://pelosi.house.gov/",
    sourceUrl: "https://www.congress.gov/member/nancy-pelosi/P000197",
    description: "House member from California's 11th District included for San Francisco district matching in Round 3 beta testing."
  },
  {
    bioguideId: "J000294",
    firstName: "Hakeem",
    lastName: "Jeffries",
    fullName: "Rep. Hakeem S. Jeffries",
    party: "Democrat",
    state: "NY",
    district: "8",
    chamber: "House",
    active: true,
    term: "119th Congress",
    termsInOffice: 7,
    firstElectedDate: "2012-11-06",
    nextElectionDate: "2026-11-03",
    photoUrl: "https://www.congress.gov/img/member/j000294_200.jpg",
    officialUrl: "https://jeffries.house.gov/",
    sourceUrl: "https://www.congress.gov/member/hakeem-jeffries/J000294",
    description: "House member from New York's 8th District included for Brooklyn district matching and leadership-profile testing."
  },
  {
    bioguideId: "M000312",
    firstName: "James",
    lastName: "McGovern",
    fullName: "Rep. James P. McGovern",
    party: "Democrat",
    state: "MA",
    district: "2",
    chamber: "House",
    active: true,
    term: "119th Congress",
    termsInOffice: 15,
    firstElectedDate: "1996-11-05",
    nextElectionDate: "2026-11-03",
    photoUrl: "https://www.congress.gov/img/member/m000312_200.jpg",
    officialUrl: "https://mcgovern.house.gov/",
    sourceUrl: "https://www.congress.gov/member/james-mcgovern/M000312",
    description: "House member from Massachusetts's 2nd District included for Worcester district matching in the expanded beta dataset."
  }
];

export const members: Member[] = memberRecords.map(withMemberServiceFallback);

export const bills: Bill[] = [
  {
    id: "demo-hr-22",
    congress: 119,
    billType: "HR",
    billNumber: "22",
    displayNumber: "H.R. 22",
    title: "Safeguard American Voter Eligibility Act",
    shortTitle: "SAVE Act",
    sponsorBioguideId: "R000614",
    policyArea: "Government Operations and Politics",
    introducedDate: "2025-01-03",
    committeeName: "House Administration",
    latestActionText: "Received in the Senate after passing the House.",
    latestActionDate: "2025-04-10",
    summary:
      "Congress.gov describes this bill as requiring documentary proof of U.S. citizenship for federal voter registration and directing states to maintain voter rolls for U.S. citizens only.",
    sourceUrl: "https://www.congress.gov/bill/119th-congress/house-bill/22"
  },
  {
    id: "demo-hr-471",
    congress: 119,
    billType: "HR",
    billNumber: "471",
    displayNumber: "H.R. 471",
    title: "Fix Our Forests Act",
    shortTitle: "Fix Our Forests Act",
    sponsorBioguideId: "W000821",
    policyArea: "Public Lands and Natural Resources",
    introducedDate: "2025-01-16",
    committeeName: "House Natural Resources / Senate Agriculture",
    latestActionText: "Senate Agriculture subcommittee hearing held after House passage.",
    latestActionDate: "2025-03-06",
    summary:
      "Congress.gov summarizes this bill as addressing forest management and wildfire risk, including fireshed planning, a wildfire intelligence center, and expedited environmental review tools.",
    sourceUrl: "https://www.congress.gov/bill/119th-congress/house-bill/471"
  },
  {
    id: "demo-s-2237",
    congress: 119,
    billType: "S",
    billNumber: "2237",
    displayNumber: "S. 2237",
    title: "Hospital Inpatient Services Modernization Act",
    shortTitle: "Hospital Inpatient Services Modernization Act",
    sponsorBioguideId: "S001184",
    policyArea: "Health",
    introducedDate: "2025-07-10",
    committeeName: "Senate Finance Committee",
    latestActionText: "Read twice and referred to the Senate Finance Committee.",
    latestActionDate: "2025-07-10",
    summary:
      "Congress.gov lists this health bill as introduced and referred to Senate Finance. The official CRS summary is still in progress, so Capitol Ledger keeps the record clearly marked as pending deeper summary text.",
    sourceUrl: "https://www.congress.gov/bill/119th-congress/senate-bill/2237"
  },
  {
    id: "demo-s-3688",
    congress: 119,
    billType: "S",
    billNumber: "3688",
    displayNumber: "S. 3688",
    title: "RURAL Rate Act",
    shortTitle: "RURAL Rate Act",
    sponsorBioguideId: "S001198",
    policyArea: "Social Welfare",
    introducedDate: "2026-01-15",
    committeeName: "Senate Finance Committee",
    latestActionText: "Read twice and referred to the Senate Finance Committee.",
    latestActionDate: "2026-01-15",
    summary:
      "Congress.gov lists this Alaska-sponsored social welfare bill as introduced and referred to Senate Finance. The official CRS summary is still in progress.",
    sourceUrl: "https://www.congress.gov/bill/119th-congress/senate-bill/3688"
  }
];

export const cosponsors: Cosponsor[] = [
  { billId: "demo-hr-22", memberBioguideId: "M001157", joinedAt: "2025-01-03" },
  { billId: "demo-s-2237", memberBioguideId: "W000790", joinedAt: "2025-07-10" }
];

export const billVideos: BillVideo[] = [
  {
    id: "video-hr-22-house-vote",
    billId: "demo-hr-22",
    title: "House roll-call vote on H.R. 22",
    speaker: "Office of the Clerk",
    role: "Official vote source",
    source: "Office of the Clerk",
    sourceKind: "Official vote record",
    verifiedAt: "2026-06-17",
    publishedAt: "2025-04-10",
    duration: "Recorded vote",
    videoUrl: "https://clerk.house.gov/Votes/2025102",
    type: "Public Statement",
    summary: "Official House vote record for passage of H.R. 22 in the 119th Congress."
  },
  {
    id: "video-hr-22-actions",
    billId: "demo-hr-22",
    title: "Congress.gov actions for H.R. 22",
    speaker: "Congress.gov",
    role: "Official bill action source",
    source: "Congress.gov",
    sourceKind: "Official bill record",
    verifiedAt: "2026-06-17",
    publishedAt: "2025-04-10",
    duration: "Action history",
    videoUrl: "https://www.congress.gov/bill/119th-congress/house-bill/22/all-actions",
    type: "Public Statement",
    summary: "Official action history showing H.R. 22 passing the House and being received in the Senate."
  },
  {
    id: "video-hr-471-house-vote",
    billId: "demo-hr-471",
    title: "House roll-call vote on H.R. 471",
    speaker: "Office of the Clerk",
    role: "Official vote source",
    source: "Office of the Clerk",
    sourceKind: "Official vote record",
    verifiedAt: "2026-06-17",
    publishedAt: "2025-01-23",
    duration: "Recorded vote",
    videoUrl: "https://clerk.house.gov/Votes/2025025",
    type: "Public Statement",
    summary: "Official House vote record for passage of the Fix Our Forests Act."
  },
  {
    id: "video-hr-471-actions",
    billId: "demo-hr-471",
    title: "Congress.gov actions for H.R. 471",
    speaker: "Congress.gov",
    role: "Official bill action source",
    source: "Congress.gov",
    sourceKind: "Official bill record",
    verifiedAt: "2026-06-17",
    publishedAt: "2025-03-06",
    duration: "Action history",
    videoUrl: "https://www.congress.gov/bill/119th-congress/house-bill/471/all-actions",
    type: "Public Statement",
    summary: "Official action history for H.R. 471, including House passage and Senate committee activity."
  },
  {
    id: "video-s-2237-record",
    billId: "demo-s-2237",
    title: "Congress.gov record for S. 2237",
    speaker: "Congress.gov",
    role: "Official bill source",
    source: "Congress.gov",
    sourceKind: "Official bill record",
    verifiedAt: "2026-06-17",
    publishedAt: "2025-07-10",
    duration: "Bill record",
    videoUrl: "https://www.congress.gov/bill/119th-congress/senate-bill/2237",
    type: "Public Statement",
    summary: "Official Congress.gov record for S. 2237 and its Senate Finance referral."
  },
  {
    id: "video-s-3688-record",
    billId: "demo-s-3688",
    title: "Congress.gov record for S. 3688",
    speaker: "Congress.gov",
    role: "Official bill source",
    source: "Congress.gov",
    sourceKind: "Official bill record",
    verifiedAt: "2026-06-17",
    publishedAt: "2026-01-15",
    duration: "Bill record",
    videoUrl: "https://www.congress.gov/bill/119th-congress/senate-bill/3688",
    type: "Public Statement",
    summary: "Official Congress.gov record for S. 3688 and its Senate Finance referral."
  }
];

export const votes: Vote[] = [
  {
    id: "demo-vote-house-102",
    congress: 119,
    chamber: "House",
    rollCall: "102",
    question: "On passage of H.R. 22",
    result: "Passed",
    voteDate: "2025-04-10",
    yesCount: 220,
    noCount: 208,
    presentCount: 0,
    notVotingCount: 7,
    billId: "demo-hr-22",
    explanation: "Official House roll call 102 recorded passage of H.R. 22 before the bill was received in the Senate.",
    sourceUrl: "https://clerk.house.gov/Votes/2025102"
  },
  {
    id: "demo-vote-house-25",
    congress: 119,
    chamber: "House",
    rollCall: "25",
    question: "On passage of H.R. 471",
    result: "Passed",
    voteDate: "2025-01-23",
    yesCount: 279,
    noCount: 141,
    presentCount: 0,
    notVotingCount: 15,
    billId: "demo-hr-471",
    explanation: "Official House roll call 25 recorded passage of the Fix Our Forests Act.",
    sourceUrl: "https://clerk.house.gov/Votes/2025025"
  }
];

const hr22ActionsSourceUrl = "https://www.congress.gov/bill/119th-congress/house-bill/22/all-actions";

export const billActions: BillAction[] = [
  {
    id: "demo-hr-22-action-20250103-introduced",
    billId: "demo-hr-22",
    action: "Introduced in House",
    chamber: "House",
    date: "2025-01-03",
    kind: "Introduced",
    occurredAt: "2025-01-03",
    sourceLabel: "Congress.gov All Actions",
    sourceSystem: "Congress.gov",
    sourceUrl: hr22ActionsSourceUrl,
    timePrecision: "date"
  },
  {
    id: "demo-hr-22-action-20250103-referred",
    billId: "demo-hr-22",
    action: "Referred to the House Committee on House Administration.",
    chamber: "House",
    date: "2025-01-03",
    kind: "Committee",
    occurredAt: "2025-01-03",
    sourceLabel: "Congress.gov All Actions",
    sourceSystem: "Congress.gov",
    sourceUrl: hr22ActionsSourceUrl,
    timePrecision: "date"
  },
  {
    id: "demo-hr-22-action-20250401-rules-reported",
    billId: "demo-hr-22",
    action: "Rules Committee Resolution H. Res. 282 Reported to House. Rule provides for consideration of H.R. 22, H.R. 1526, S.J. Res. 18 and S.J. Res. 28. The resolution provides for one hour of debate on each measure and one motion to recommit on H.R. 22 and H.R. 1526, and one motion to commit on S.J. Res. 18 and S.J. Res. 28.",
    chamber: "House",
    date: "2025-04-01",
    kind: "Committee",
    occurredAt: "2025-04-01T10:03:00",
    sourceLabel: "Congress.gov All Actions",
    sourceSystem: "Congress.gov",
    sourceUrl: hr22ActionsSourceUrl,
    time: "10:03am",
    timePrecision: "minute"
  },
  {
    id: "demo-hr-22-action-20250407-rules-reported",
    billId: "demo-hr-22",
    action: "Rules Committee Resolution H. Res. 294 Reported to House. Rule provides for consideration of S.J. Res. 18, S.J. Res. 28, H.R. 1526 and H.R. 22 under a closed rule.",
    chamber: "House",
    date: "2025-04-07",
    kind: "Committee",
    occurredAt: "2025-04-07T19:20:00",
    sourceLabel: "Congress.gov All Actions",
    sourceSystem: "Congress.gov",
    sourceUrl: hr22ActionsSourceUrl,
    time: "7:20pm",
    timePrecision: "minute"
  },
  {
    id: "demo-hr-22-action-20250408-rule-passed",
    billId: "demo-hr-22",
    action: "Rule H. Res. 294 passed House.",
    chamber: "House",
    date: "2025-04-08",
    kind: "Floor",
    occurredAt: "2025-04-08T15:23:00",
    sourceLabel: "Congress.gov All Actions",
    sourceSystem: "Congress.gov",
    sourceUrl: hr22ActionsSourceUrl,
    time: "3:23pm",
    timePrecision: "minute"
  },
  {
    id: "demo-hr-22-action-20250410-considered-rule",
    billId: "demo-hr-22",
    action: "Considered under the provisions of rule H. Res. 294. (consideration: CR H1569-1579)",
    chamber: "House",
    date: "2025-04-10",
    kind: "Floor",
    occurredAt: "2025-04-10T09:19:00",
    sourceLabel: "Congress.gov All Actions",
    sourceSystem: "Congress.gov",
    sourceUrl: hr22ActionsSourceUrl,
    time: "9:19am",
    timePrecision: "minute"
  },
  {
    id: "demo-hr-22-action-20250410-rule-provides",
    billId: "demo-hr-22",
    action: "Rule provides for consideration of S.J. Res. 18, S.J. Res. 28, H.R. 1526 and H.R. 22. The resolution provides for one hour of debate on each measure and one motion to recommit on H.R. 22 and H.R. 1526.",
    chamber: "House",
    date: "2025-04-10",
    kind: "Procedural",
    occurredAt: "2025-04-10T09:19:00",
    sourceLabel: "Congress.gov All Actions",
    sourceSystem: "Congress.gov",
    sourceUrl: hr22ActionsSourceUrl,
    time: "9:19am",
    timePrecision: "minute"
  },
  {
    id: "demo-hr-22-action-20250410-debate",
    billId: "demo-hr-22",
    action: "DEBATE - The House proceeded with one hour of debate on H.R. 22.",
    chamber: "House",
    date: "2025-04-10",
    kind: "Floor",
    occurredAt: "2025-04-10T09:19:00",
    sourceLabel: "Congress.gov All Actions",
    sourceSystem: "Congress.gov",
    sourceUrl: hr22ActionsSourceUrl,
    time: "9:19am",
    timePrecision: "minute"
  },
  {
    id: "demo-hr-22-action-20250410-previous-question",
    billId: "demo-hr-22",
    action: "The previous question was ordered pursuant to the rule.",
    chamber: "House",
    date: "2025-04-10",
    kind: "Procedural",
    occurredAt: "2025-04-10T10:30:00",
    sourceLabel: "Congress.gov All Actions",
    sourceSystem: "Congress.gov",
    sourceUrl: hr22ActionsSourceUrl,
    time: "10:30am",
    timePrecision: "minute"
  },
  {
    id: "demo-hr-22-action-20250410-recommit-motion",
    billId: "demo-hr-22",
    action: "Ms. Johnson (TX) moved to recommit to the Committee on House Administration. (text: CR H1569)",
    chamber: "House",
    date: "2025-04-10",
    kind: "Procedural",
    occurredAt: "2025-04-10T10:30:00",
    sourceLabel: "Congress.gov All Actions",
    sourceSystem: "Congress.gov",
    sourceUrl: hr22ActionsSourceUrl,
    time: "10:30am",
    timePrecision: "minute"
  },
  {
    id: "demo-hr-22-action-20250410-recommit-previous-question",
    billId: "demo-hr-22",
    action: "The previous question on the motion to recommit was ordered pursuant to clause 2(b) of rule XIX.",
    chamber: "House",
    date: "2025-04-10",
    kind: "Procedural",
    occurredAt: "2025-04-10T10:31:00",
    sourceLabel: "Congress.gov All Actions",
    sourceSystem: "Congress.gov",
    sourceUrl: hr22ActionsSourceUrl,
    time: "10:31am",
    timePrecision: "minute"
  },
  {
    id: "demo-hr-22-action-20250410-postponed",
    billId: "demo-hr-22",
    action: "POSTPONED PROCEEDINGS - At the conclusion of debate on H.R. 22, the Chair put the question on motion to recommit and by voice vote, announced the noes had prevailed. Ms. Johnson (TX) demanded the yeas and nays and the Chair postponed further proceedings until a time to be announced.",
    chamber: "House",
    date: "2025-04-10",
    kind: "Procedural",
    occurredAt: "2025-04-10T10:31:00",
    sourceLabel: "Congress.gov All Actions",
    sourceSystem: "Congress.gov",
    sourceUrl: hr22ActionsSourceUrl,
    time: "10:31am",
    timePrecision: "minute"
  },
  {
    id: "demo-hr-22-action-20250410-unfinished",
    billId: "demo-hr-22",
    action: "Considered as unfinished business. (consideration: CR H1580-1581)",
    chamber: "House",
    date: "2025-04-10",
    kind: "Floor",
    occurredAt: "2025-04-10T11:11:00",
    sourceLabel: "Congress.gov All Actions",
    sourceSystem: "Congress.gov",
    sourceUrl: hr22ActionsSourceUrl,
    time: "11:11am",
    timePrecision: "minute"
  },
  {
    id: "demo-hr-22-action-20250410-roll-101",
    billId: "demo-hr-22",
    action: "On motion to recommit Failed by the Yeas and Nays: 211 - 215 (Roll no. 101).",
    chamber: "House",
    date: "2025-04-10",
    kind: "Vote",
    occurredAt: "2025-04-10T11:17:00",
    rollCall: "101",
    sourceLabel: "Congress.gov All Actions",
    sourceSystem: "Congress.gov",
    sourceUrl: hr22ActionsSourceUrl,
    time: "11:17am",
    timePrecision: "minute"
  },
  {
    id: "demo-hr-22-action-20250410-roll-102",
    billId: "demo-hr-22",
    action: "On passage Passed by the Yeas and Nays: 220 - 208 (Roll no. 102). (text: CR H1569-1571)",
    chamber: "House",
    date: "2025-04-10",
    kind: "Vote",
    linkedVoteId: "demo-vote-house-102",
    occurredAt: "2025-04-10T11:23:00",
    rollCall: "102",
    sourceLabel: "Congress.gov All Actions",
    sourceSystem: "Congress.gov",
    sourceUrl: hr22ActionsSourceUrl,
    time: "11:23am",
    timePrecision: "minute"
  },
  {
    id: "demo-hr-22-action-20250410-reconsider",
    billId: "demo-hr-22",
    action: "Motion to reconsider laid on the table Agreed to without objection.",
    chamber: "House",
    date: "2025-04-10",
    kind: "Procedural",
    occurredAt: "2025-04-10T11:23:00",
    sourceLabel: "Congress.gov All Actions",
    sourceSystem: "Congress.gov",
    sourceUrl: hr22ActionsSourceUrl,
    time: "11:23am",
    timePrecision: "minute"
  },
  {
    id: "demo-hr-22-action-20250410-senate-received",
    billId: "demo-hr-22",
    action: "Received in the Senate.",
    chamber: "Senate",
    date: "2025-04-10",
    kind: "Chamber Transfer",
    occurredAt: "2025-04-10",
    sourceLabel: "Congress.gov All Actions",
    sourceSystem: "Congress.gov",
    sourceUrl: hr22ActionsSourceUrl,
    timePrecision: "date"
  }
];

export const memberVotes: MemberVote[] = [
  { voteId: "demo-vote-house-102", memberBioguideId: "R000614", position: "Yes" },
  { voteId: "demo-vote-house-102", memberBioguideId: "M001157", position: "Yes" },
  { voteId: "demo-vote-house-102", memberBioguideId: "FCA030", position: "No" },
  { voteId: "demo-vote-house-102", memberBioguideId: "O000172", position: "No" },
  { voteId: "demo-vote-house-102", memberBioguideId: "P000197", position: "No" },
  { voteId: "demo-vote-house-25", memberBioguideId: "W000821", position: "Yes" },
  { voteId: "demo-vote-house-25", memberBioguideId: "J000294", position: "No" },
  { voteId: "demo-vote-house-25", memberBioguideId: "M000312", position: "No" }
];

export const updateEvents: UpdateEvent[] = [
  {
    id: "event-1",
    targetType: "bill",
    targetId: "demo-hr-22",
    title: "Bill passed the House",
    body: "H.R. 22 passed the House and was received in the Senate.",
    occurredAt: "2025-04-10",
    sourceUrl: "https://www.congress.gov/bill/119th-congress/house-bill/22"
  },
  {
    id: "event-2",
    targetType: "bill",
    targetId: "demo-hr-471",
    title: "Senate hearing held",
    body: "H.R. 471 had Senate Agriculture subcommittee activity after House passage.",
    occurredAt: "2025-03-06",
    sourceUrl: "https://www.congress.gov/bill/119th-congress/house-bill/471"
  },
  {
    id: "event-3",
    targetType: "bill",
    targetId: "demo-s-3688",
    title: "Bill introduced",
    body: "S. 3688 was introduced and referred to the Senate Finance Committee.",
    occurredAt: "2026-01-15",
    sourceUrl: "https://www.congress.gov/bill/119th-congress/senate-bill/3688"
  }
];
